run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  disable-all: true
  enable:
    # Default linters
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    # Formatting
    - gofmt
    - goimports
    - misspell
    # Error handling
    - errcheck
    - bodyclose
    # Code quality
    - goconst
    - unconvert
    # Security
    - gosec

linters-settings:
  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/jjuanrivvera/canvas-cli

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
