run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - goimports
    - misspell

linters-settings:
  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/jjuanrivvera/canvas-cli

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
