# GoReleaser configuration for Canvas CLI
# See: https://goreleaser.com/customization/

version: 2

before:
  hooks:
    # Run tests before building
    - go test ./...
    # Run mod tidy to ensure dependencies are clean
    - go mod tidy

builds:
  - id: canvas
    main: ./cmd/canvas
    binary: canvas
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ignore:
      # Windows on ARM is not common yet
      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser

archives:
  - id: canvas
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - CHANGELOG.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: 'Bug Fixes'
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: 'Performance Improvements'
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999

release:
  github:
    owner: jjuanrivvera
    name: canvas-cli
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## Canvas CLI {{.Version}}

    ### Installation

    #### Using Homebrew (macOS/Linux)
    ```bash
    brew tap jjuanrivvera/canvas-cli
    brew install canvas-cli
    ```

    #### Using Go
    ```bash
    go install github.com/jjuanrivvera/canvas-cli/cmd/canvas@{{.Tag}}
    ```

    #### Manual Download
    Download the appropriate binary for your platform from the assets below.

  footer: |
    **Full Changelog**: https://github.com/jjuanrivvera/canvas-cli/compare/{{.PreviousTag}}...{{.Tag}}

    ---

    ### Upgrading

    If you installed via Homebrew:
    ```bash
    brew upgrade canvas-cli
    ```

    If you installed manually, download the latest version from the assets above.

# Homebrew tap configuration
brews:
  - repository:
      owner: jjuanrivvera
      name: homebrew-canvas-cli
    directory: Formula
    homepage: https://github.com/jjuanrivvera/canvas-cli
    description: Command-line interface for Canvas LMS
    license: MIT
    test: |
      system "#{bin}/canvas version"
    install: |
      bin.install "canvas"

      # Install shell completions
      bash_completion.install "completions/canvas.bash" => "canvas"
      zsh_completion.install "completions/_canvas" => "_canvas"
      fish_completion.install "completions/canvas.fish"

# Scoop manifest for Windows
scoop:
  bucket:
    owner: jjuanrivvera
    name: scoop-bucket
  homepage: https://github.com/jjuanrivvera/canvas-cli
  description: Command-line interface for Canvas LMS
  license: MIT

# Docker images
dockers:
  - image_templates:
      - "ghcr.io/jjuanrivvera/canvas-cli:{{ .Tag }}"
      - "ghcr.io/jjuanrivvera/canvas-cli:v{{ .Major }}"
      - "ghcr.io/jjuanrivvera/canvas-cli:v{{ .Major }}.{{ .Minor }}"
      - "ghcr.io/jjuanrivvera/canvas-cli:latest"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

# Announce release
announce:
  skip: "true"

# Sign the checksums file with GPG
signs:
  - artifacts: checksum
    args:
      - "--batch"
      - "--local-user"
      - "{{ .Env.GPG_FINGERPRINT }}"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"

# Create SBOMs (Software Bill of Materials)
sboms:
  - artifacts: archive

# Metadata
metadata:
  mod_timestamp: '{{ .CommitTimestamp }}'
